spring:
  datasource:
    url: jdbc:mysql://8.138.144.45:3306/dg?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: zjxzzjxzmysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 8.138.144.45
    port: 6379
    database: 0
    timeout: 1800000
    password: cclcclredis
    lettuce:
      pool:
        max-active: 20 # 连接池最大连接数
        max-idle: 5 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间
