spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dg?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10s
    password:
    lettuce:
      pool:
        max-idle: 5 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-active: 20 # 连接池最大连接数
        max-wait: -1ms # 连接池最大阻塞等待时间
